allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - markdown-it@14.1.1
  - esbuild@0.28.1
  - js-yaml@4.1.2
  - markdown-it@14.1.2
onlyBuiltDependencies:
  - esbuild
overrides:
  js-yaml: ^4.1.2
  markdown-it: ^14.1.2
